name: Run AQAvit 

on:
  workflow_dispatch: # Allows the job to be manually triggered

env:  # Links to the JDK build under test and the native test libs
  USE_TESTENV_PROPERTIES: false
  CUSTOMIZED_SDK_URL: https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.14.1%2B1/OpenJDK11U-jdk_x64_linux_hotspot_11.0.14.1_1.tar.gz
  
jobs:
  run_aqa:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:

    - name: Run AQA Tests - ${{ matrix.target }}.${{ matrix.suite }}
      uses: adoptium/run-aqa@v2
      with: 
        jdksource: 'customized'
        customizedSdkUrl: ${{ env.CUSTOMIZED_SDK_URL }} 
        aqa-testsRepo: 'adoptium/aqa-tests:master' 
        build_list: 'system/jcstress'
        target: '_dev.system'

    - uses: actions/upload-artifact@v2
      if: always() # Always run this step (even if the tests failed)
      with:
        name: test_output
        path: ./**/output_*/*.tap
