name: Run AQAvit system/jcstress dev level targets in parallel

on:
  workflow_dispatch: # Allows the job to be manually triggered
    inputs:
      customizedSdkUrl:
         description: JDK binary download link
         required: true
      runParallel:
        description: Run tests in parallel
        required: true
        type: boolean
      runner:
        description: runner
        required: true
        type: choice
        options:
          - ubuntu-latest
          - windows-2019
          - macos-11
  
jobs:
  setup-parallel:
    runs-on: ${{ inputs.runner }}
    if: ${{ inputs.runParallel == true }}
    name: setup-parallel - ${{ inputs.runner }}_dev.system
    strategy:
      fail-fast: true

    steps:
      - uses: adoptium/run-aqa@master
        name: Generate parallelList - system/jcstress dev level targets
        with:
          jdksource: 'customized'
          customizedSdkUrl: ${{ inputs.customizedSdkUrl }}
          aqa-testsRepo: 'jabrena/aqa-tests:feature/dynamic-jcstress-playlist' 
          build_list: system/jcstress
          target: _dev.system
          run_parallel: ${{ inputs.runParallel }}
          num_machines: 4 # number of machines we want to run

      - name: Archive parallelList - dev.system
        uses: actions/upload-artifact@v2
        with:
          name: dev.system-parallelList.mk
          path: ${{ github.workspace }}/aqa-tests/TKG/parallelList.mk
          
  run-aqa-parallel:
    runs-on: ${{ inputs.runner }}
    if: ${{ inputs.runParallel == true }}
    needs: setup-parallel
    name: Run AQAvit ${{ inputs.runner }} - dev.system.${{ matrix.test_list }}
    strategy:
      fail-fast: false
      matrix:
        test_list: ['testList_0', 'testList_1', 'testList_2', 'testList_3'] # numlist is hardcoded   
    steps:
        # download the paralleList to the current working directory
      - name: Download parallelList - dev.system
        uses: actions/download-artifact@v2
        with:
          name: dev.system-parallelList.mk
          path: ./

      - name: Run AQA Parallel Test - dev.system_${{ matrix.test_list }}
        uses: adoptium/run-aqa@master
        with:
          jdksource: 'customized'
          customizedSdkUrl: ${{ inputs.customizedSdkUrl }}
          aqa-testsRepo: 'adoptium/aqa-tests:v0.9.4-release' # Make sure this branch is set to the latest release branch
          build_list: system/jcstress
          target : -f parallelList.mk ${{ matrix.test_list }}

      - uses: actions/upload-artifact@v2
        if: always() # Always run this step (even if the tests failed)
        with:
          name: test_output_dev.system_${{ matrix.test_list }}
          path: ./**/output_*/*.tap
